### ISSUE TITLE
Grunt task for free and gold version

### ISSUE THREAD

**Issue by pixelstrolch** [WPZOO/penguin-gold#10]
- [x] Name
- [x] <del>Using different styles (sidebar layout, scroll to top, menu, …)</del>
- [x] page-fullwidth.php
- [x] Using additional code in extra-penguin-gold.php, customizer-options-gold.php, customizer-styles-gold.php
- [x] Differences in function _Enqueue scripts and styles_ (currently in functions.php)
- [x] Minified css and js only for gold version
- [x] Icon font doesn't work in lite version

**Comment by grappler** [comment]
The plan is to first copy the files that are needed in the free version into a new folder `penguin`. The second step is to rename the theme name. The third step will be to remove the loading code for files that are not included. 

The reason for doing it this way is so that the two versions can be tested easily.

**Comment by grappler** [comment]
Are there anything else you need removed from the Gold version? There are a few things in the first comment but I can't remember exactly what I meant with it.

**Comment by pixelstrolch** [comment]
I updated the list above. I'm not sure, did we decide to let the gold styles in?

**Comment by grappler** [comment]
What Gold specific styles do we have?

**Comment by pixelstrolch** [comment]
You can forget that. Since there is not much additional code, I believe we decided to keep it also for the lite version 0c5f2bb.

**Comment by pixelstrolch** [comment]
There is an issue with the icon font only in the lite version:
```
Failed to decode downloaded font: http://local.wordpress.dev/wp-content/themes/penguin/fonts/penguin-icon-font.woff2
OTS parsing error: Failed to convert WOFF 2.0 font to SFNT
Failed to decode downloaded font: http://local.wordpress.dev/wp-content/themes/penguin/fonts/penguin-icon-font.woff
OTS parsing error: incorrect file size in WOFF header
Failed to decode downloaded font: http://local.wordpress.dev/wp-content/themes/penguin/fonts/penguin-icon-font.ttf
OTS parsing error: incorrect entrySelector for table directory
```

**Comment by grappler** [comment]
The fonts should be fixed with https://github.com/WPZOO/grunt/commit/8ebc2566aa82f0e5fda2548e721617172b19af2f

**Comment by grappler** [comment]
What do you mean by:?
>  Differences in function Enqueue scripts and styles (currently in functions.php)

**Comment by grappler** [comment]
This is now completed.
