### ISSUE TITLE
Use header image for the logo instead of creating a separate option

### ISSUE THREAD

**Issue by grappler** [WPZOO/penguin-gold#20]
We should use the header image instead of creating a separate logo option.
We should also add the images size to the HTML [header.php#L37](https://github.com/WPZOO/penguin-gold/blob/master/header.php#L37)

You could copy the code from [_s/inc/custom-header.php](https://github.com/Automattic/_s/blob/master/inc/custom-header.php)

**Comment by pixelstrolch** [comment]
The cropping window is not needed and displays an error when clicking *Crop image*. Is there a solution? Perhaps disable the crop function? d008a97

**Comment by pixelstrolch** [comment]
Due to the cropping issues, we're keeping it in a separate option. ea44705
