### ISSUE TITLE
README.html

### ISSUE THREAD

**Issue by grappler** [WPZOO/penguin-gold#22]
The image urls in README.html are not relative e.g. `/Applications/MAMP/htdocs/penguin/wp-content/themes/penguin-gold/screenshot.png`

**Comment by pixelstrolch** [comment]
@grappler I compiled the md files with a Sublime Extension which is probably not the best way. What do you think about compiling all existing markdown files with grunt? The inline styles doesn't have to be the same.

**Comment by grappler** [comment]
Possible grunt tasks: https://github.com/treasonx/grunt-markdown / https://github.com/bylexus/grunt-md2html

Are planning of linking to the html version in the theme?

**Comment by pixelstrolch** [comment]
I think many users don't know the markdown suffix, but they know how to open a html document. I thought it's easier to compile a html document rather than creating an extra txt file. Which links do you mean? What's your opinion on that? I can live without these html files.

**Comment by grappler** [comment]
We decided to have no HTML version.
