### ISSUE TITLE
Release 0.2

### ISSUE THREAD

**Issue by pixelstrolch** [WPZOO/penguin-gold#26]
- [x] Support sizes attribute
- [ ] <del>Improve form styles</del> (Consider in a further release)
- [x] Add a few editor styles
- [x] Using flexbox for comment form (already in 0.1.2)
- [x] Use svg icons instead of icon font
- [x] Custom logo via add_theme_support

**Comment by pixelstrolch** [comment]
@grappler Any ideas how to show the arrow down icon for menus with submenus? See the initial svg commit 1db420d

**Comment by grappler** [comment]
So, you need to add custom markup to those menu items that have a sub menu?
