### ISSUE TITLE
Translations

### ISSUE THREAD

**Issue by pixelstrolch** [WPZOO/penguin-gold#3]
- Check any English strings
- Create POT-File
- Translate to German

**Comment by grappler** [comment]
The support should be complete:
- Penguin will load the translations from `wp-content/languages/themes/penguin-de_de.mo`
- Penguin Gold will load the rest of the translations from `wp-content/themes/penguin-gold/languages/de_de.mo` for the strings only in gold.

**Comment by grappler** [comment]
I was able to install a translation pack for a plugin that is not hosted on WordPress.org. I am looking into how to further integrate it in Penguin Gold.
